const colorNames = {
  black: '#000000',
  white: '#ffffff',
  gray: '#808080',
  indigo: '#6d46f0',
  transparent: 'rgba(255, 255, 255, 0.1)',
  transparent2: 'rgba(0, 0, 0, 0.5)',
  transparentInput: 'rgba(0, 0, 0, 0.3)',
  blue: '#00a2c6',
  stone: '#252626',
  lightGray: '#f2f4f5',
  green: '#24ad29',
  orange: '#ff9100',
  red: '#c90000',
  turquoiseSurf: '#00B9D4',
  darkGray: '#3b4145',
  yellow: '#F7B217',
  yellow2: '#edfa75',
  darkOrange: '#ff9100',
  darkBlue: '#00A2C6',
  lightGray2: '#ebebeb',
  midGray: '#dcdde1',
  purple: '#ff69f2',
};

export default {
  button: {
    primary: colorNames.orange,
    transparent: colorNames.transparent,
    red: colorNames.red,
    warning: colorNames.yellow,
    indigo: colorNames.indigo,
    disabled: colorNames.gray,
    secondary: colorNames.turquoiseSurf,
    tertiary: colorNames.stone,
  },
  text: {
    primary: colorNames.orange,
    white: colorNames.white,
    black: colorNames.black,
    indigo: colorNames.indigo,
    blue: colorNames.blue,
    stone: colorNames.stone,
    green: colorNames.green,
    gray: colorNames.gray,
    orange: colorNames.orange,
    red: colorNames.red,
    darkGray: colorNames.darkGray,
    midGray: colorNames.midGray,
    darkBlue: colorNames.darkBlue,
  },
  input: {
    transparent: colorNames.transparentInput,
  },
  backgroundColor: {
    primary: colorNames.white,
    secondary: colorNames.turquoiseSurf,
    tertiary: colorNames.lightGray,
    green: colorNames.green,
    orange: colorNames.yellow,
    stone: colorNames.stone,
    red: colorNames.red,
    transparent: colorNames.transparent2,
    darkOrange: colorNames.darkOrange,
    darkGray: colorNames.darkGray,
    midGray: colorNames.midGray,
    purple: colorNames.purple,
    yellow: colorNames.yellow2,
  },
  card: {
    primary: colorNames.white,
  },
  border: {
    primary: colorNames.transparentInput,
    secondary: colorNames.stone,
    tertiary: colorNames.turquoiseSurf,
    light: colorNames.gray,
    red: colorNames.red,
    green: colorNames.green,
    blue: colorNames.blue,
    orange: colorNames.orange,
    lightGray: colorNames.lightGray2,
  },
};
